// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbqxtxzcchilvaxvflbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicXh0eHpjY2hpbHZheHZmbGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxOTM2MzYsImV4cCI6MjA3MTc2OTYzNn0.1NjygTHZy7nPN--XKizBCOJgG3dPm5qVplCOCUdsVo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});